MinhaGrana/Controllers/DefaultController.cs
using MinhaGrana.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinhaGrana.Controllers
{
    public class DefaultController : Controller
    {
        private GranaContext db = new GranaContext();

        [HttpPost]
        public string FiltrarDespesas(string DataIni, string DataFim)
        {
        
            return "A data é: " + DataIni + " e " + DataFim;
        }
    }
}

MinhaGrana/Controllers/FiltroRelatorioDespesasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MinhaGrana.Models;

namespace MinhaGrana.Controllers
{
    public class FiltroRelatorioDespesasController : Controller
    {
        private GranaContext db = new GranaContext();

        // GET: Despesas1
        public ActionResult Index()
        {
            var despesas = db.Despesas.Include(d => d.Categoria);
            return View(despesas.ToList());
        }

        // GET: Despesas1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesas despesas = db.Despesas.Find(id);
            if (despesas == null)
            {
                return HttpNotFound();
            }
            return View(despesas);
        }

        // GET: Despesas1/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "Nome");
            return View();
        }

        // POST: Despesas1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Valor,Data,Descricao,DespesaFixa,CategoriaId")] Despesas despesas)
        {
            if (ModelState.IsValid)
            {
                db.Despesas.Add(despesas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "Nome", despesas.CategoriaId);
            return View(despesas);
        }

        // GET: Despesas1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesas despesas = db.Despesas.Find(id);
            if (despesas == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "Nome", despesas.CategoriaId);
            return View(despesas);
        }

        // POST: Despesas1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Valor,Data,Descricao,DespesaFixa,CategoriaId")] Despesas despesas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(despesas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "Id", "Nome", despesas.CategoriaId);
            return View(despesas);
        }

        // GET: Despesas1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesas despesas = db.Despesas.Find(id);
            if (despesas == null)
            {
                return HttpNotFound();
            }
            return View(despesas);
        }

        // POST: Despesas1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Despesas despesas = db.Despesas.Find(id);
            db.Despesas.Remove(despesas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MinhaGrana/Views/FiltroRelatorioDespesas/Index.cshtml
@model IEnumerable<MinhaGrana.Models.Despesas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("FiltrarDespesas", "Default", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                <label>Data inicio:</label>
                <input type="text" id="DataIni" name="inicio" class="teste" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label>Data fim:</label>
                <input type="text" id="DataFim" name="fim" class="teste" />
            </div>
        </div>
    </div>
    <p>
        <input type="submit" class="btn btn-success" value="filtrar 1" name="botao1" id="botao1" onclick="filtrar()" />
    </p>

    <p>
        <span id="msg" style="color:red;" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DespesaFixa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DespesaFixa)
            </td>

        </tr>
    }

</table>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.mask.js"></script>
@*Correção de data*@
<script src="~/Scripts/methods_pt.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("#DataIni").datepicker({
            format: 'dd/mm/yyyy',
            language: 'pt-BR'
        });
        $("#DataFim").datepicker({
            format: 'dd/mm/yyyy',
            language: 'pt-BR'
        });

    });

    function filtrar()
    {
        var dataIni = $('#DataIni').val();
        var dataFim = $('#DataFim').val();
        var url = "/Default/FiltrarDespesas";
        $.post(url, { dataIni: dataIni, dataFim: dataFim}, function (data) {
            $("#msg").html(data);
        });

        //alert(dataIni + " " + dataFim)

        //$.ajax({
        //    url: "/Default/FiltrarDespesas",    
        //    type: "POST",
        //    data: { dataIni: dataIni, dataFim: dataFim},
        //    dataType: "text",
        //    contentType: "application/json; charset=utf-8",
        //    success: function (data) {
        //        alert("certo")

        //    },
        //    error: function () {
        //        alert('error');
        //    }
        //})
    }



</script>